### ISSUE TITLE
JeaRoleCapabilities Test always reeturns $false

### ISSUE THREAD

**Issue by raandree** [ChrisLGardner/JeaDsc#19] opened 2018-12-28 11:57 UTC
I am trying to create a Role Capabilities with the JeaRoleCapabilities resource. The resource's test method seems to return $false even if the Role Capabilities file exist with the requires settings. Can you repro this as well or is it me doing something wrong? I have put already a bit of time into this and should have a fix available soon if it is an issue with the code.

``` PowerShell
configuration JeaConfig1
{
    Import-DscResource -ModuleName JeaDsc

    node 'localhost'
    {

        JeaRoleCapabilities DscDiagnosticsRead
        {
            Path = 'C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleCapabilities\DscDiagnosticsRead.psrc'
            VisibleCmdlets = "@{ Name = 'Get-DscLocalConfigurationManager'; Parameters = @{ Name = '*' } }"
            FunctionDefinitions = "@{ Name = 'Test'; ScriptBlock = { Test-DscConfiguration -Detailed } }", "@{ Name = 'GD'; ScriptBlock = { Get-Date } }"
            VisibleFunctions = 'GD', 'Test'
        }
    }
}

JeaConfig1 -OutputPath c:\JeaTest
Start-DscConfiguration -Path C:\JeaTest -Verbose -Wait -Force
```

```
localhost.mof                                                                                                                        
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/
Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer RAANDREE0 with user sid S-1-5-21-3110595715-3530629690-4267244086-1001.
VERBOSE: [RAANDREE0]: LCM:  [ Start  Set      ]
VERBOSE: [RAANDREE0]: LCM:  [ Start  Resource ]  [[JeaRoleCapabilities]DscDiagnosticsRead]
VERBOSE: [RAANDREE0]: LCM:  [ Start  Test     ]  [[JeaRoleCapabilities]DscDiagnosticsRead]
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsRead] Validating Path: C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleCapabilities\DscDiagn
osticsRead.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsRead] Checking file extension is psrc for: C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleC
apabilities\DscDiagnosticsRead.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsRead] Checking parent forlder is RoleCapabilities for: C:\Program Files\WindowsPowerShell\Modules\
JeaDsc\RoleCapabilities\DscDiagnosticsRead.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsRead] Checking Folder is in PSModulePath is psrc for: C:\Program Files\WindowsPowerShell\Modules\J
eaDsc\RoleCapabilities\DscDiagnosticsRead.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsRead] Path is a valid psrc path. Returning true.
VERBOSE: [RAANDREE0]: LCM:  [ End    Test     ]  [[JeaRoleCapabilities]DscDiagnosticsRead]  in 0.0330 seconds.
VERBOSE: [RAANDREE0]: LCM:  [ Start  Set      ]  [[JeaRoleCapabilities]DscDiagnosticsRead]
VERBOSE: [RAANDREE0]: LCM:  [ End    Set      ]  [[JeaRoleCapabilities]DscDiagnosticsRead]  in 0.0410 seconds.
VERBOSE: [RAANDREE0]: LCM:  [ End    Resource ]  [[JeaRoleCapabilities]DscDiagnosticsRead]
VERBOSE: [RAANDREE0]: LCM:  [ End    Set      ]
VERBOSE: [RAANDREE0]: LCM:  [ End    Set      ]    in  0.2200 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.315 seconds
```

**Comment by ChrisLGardner** [comment] 2018-12-29 14:00
Hi

I haven't seen that yet, I'll update my integration tests and run some manual tests to see if I can repro it.

I'd guess the problem is occurring in the Compare-Hashtable function if it's not returning correctly, probably on its comparison of scriptblocks.
________________________________

**Comment by raandree** [comment] 2018-12-30 13:54
The problem seem to be that New-PSRoleCapabilityFile slightly changes the format of scriptblocks. Hence the comparison always returns $false.

If you can repro this with the code provided in my initial post, I will polish my changes and create a new PR.

**Comment by ChrisLGardner** [comment] 2018-12-30 17:00
I'm seeing that same behaviour in my tests too. I'll do some debugging and see what I come up with but if you've got a PR then that would be great.

**Comment by ChrisLGardner** [comment] 2018-12-30 17:37
So it definitely looks like the way the comparison is being done is the problem.

**Comment by ChrisLGardner** [comment] 2019-02-16 21:43
This should now be fixed in master as I've started using the same approach as the session configuration and convert it to JSON and compare the strings. I'll get a release out to the gallery soon.

**Comment by ChrisLGardner** [comment] 2019-04-27 16:03
This should be in 0.6.0 and above. 0.6.1 includes a small bug fix so I'd recommend that one or newer.

**Closed by ChrisLGardner** 2019-04-27 16:03 UTC
Labels: bug

**Comment by raandree** [comment] 2019-05-15 00:13
Sorry, but does not seem to work. I am using version 0.6.4 and a config based on your [DemoConfig.ps1](https://github.com/ChrisLGardner/JeaDsc/blob/master/DSCClassResources/DemoConfig.ps1).

``` PowerShell
configuration Test1
{
    Import-DscResource -Module JeaDsc

    JeaRoleCapabilities DscDiagnosticsCapability
    {
        Path = 'C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleCapabilities\DscDiagnostics.psrc'
        VisibleCmdlets = "@{ Name = 'Restart-Service'; Parameters = @{ Name = 'Name'; ValidateSet = 'w32time' } }"
        #FunctionDefinitions = "@{ Name = 'Test'; ScriptBlock = { Get-Date } }"
    }
    
    JeaSessionConfiguration Endpoint
    {
        EndpointName = "DscDiagnostics"
        RoleDefinitions = "@{ 'G1' = @{ RoleCapabilities = 'DscDiagnostics' } }"
        TranscriptDirectory = 'C:\ProgramData\Jea\DscDiagnostics'        
        DependsOn = '[JeaRoleCapabilities]DscDiagnosticsCapability'
    }
}

Test1 -OutputPath d:\dsc
Start-DscConfiguration -Path d:\dsc -Wait -Verbose -Force
```

The resource ```[JeaRoleCapabilities]DscDiagnosticsCapability``` is never in the desired state as the VisibleCmdlets hashtable seems to be converted into a string.

```
VERBOSE: [RAANDREE0]: LCM:  [ Start  Test     ]  [[JeaRoleCapabilities]DscDiagnosticsCapability]
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Validating Path: C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleCapabilities\Ds
cDiagnostics.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Checking file extension is psrc for: C:\Program Files\WindowsPowerShell\Modules\JeaDsc
\RoleCapabilities\DscDiagnostics.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Checking parent forlder is RoleCapabilities for: C:\Program Files\WindowsPowerShell\Mo
dules\JeaDsc\RoleCapabilities\DscDiagnostics.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Checking Folder is in PSModulePath is psrc for: C:\Program Files\WindowsPowerShell\Mod
ules\JeaDsc\RoleCapabilities\DscDiagnostics.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Path is a valid psrc path. Returning true.
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] Existing Configuration: {
    "Path":  "C:\\Program Files\\WindowsPowerShell\\Modules\\JeaDsc\\RoleCapabilities\\DscDiagnostics.psrc",
    "VisibleCmdlets":  [
                           "System.Collections.Hashtable"
                       ]
}
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]DscDiagnosticsCapability] New COnfiguration: {
    "Path":  "C:\\Program Files\\WindowsPowerShell\\Modules\\JeaDsc\\RoleCapabilities\\DscDiagnostics.psrc",
    "VisibleCmdlets":  [
                           "@{ Name = \u0027Restart-Service\u0027; Parameters = @{ Name = \u0027Name\u0027; ValidateSet = \u0027w32time\u0027 } }"
                       ]
}
VERBOSE: [RAANDREE0]: LCM:  [ End    Test     ]  [[JeaRoleCapabilities]DscDiagnosticsCapability]  in 0.3180 seconds.
VERBOSE: [RAANDREE0]: LCM:  [ Start  Set      ]  [[JeaRoleCapabilities]DscDiagnosticsCapability]
VERBOSE: [RAANDREE0]: LCM:  [ End    Set      ]  [[JeaRoleCapabilities]DscDiagnosticsCapability]  in 0.0720 seconds.
VERBOSE: [RAANDREE0]: LCM:  [ End    Resource ]  [[JeaRoleCapabilities]DscDiagnosticsCapability]
```
